version: '3.9'
services:
  postgres:
    image: postgres
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=task
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  h2:
    image: oscarfonts/h2
    ports:
      - 8082:8082
    environment:
      - H2_OPTIONS=-ifNotExists

  redis:
    image: redis
    ports:
      - 6379:6379
