spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: test_user
    password: test_password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db.changelog/changelog-master.xml
